# Generated by Django 2.0.1 on 2019-06-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
