# Generated by Django 2.0.1 on 2019-06-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190625_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='content',
        ),
        migrations.AddField(
            model_name='quiz',
            name='times_taken',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.SmallIntegerField(default=4),
        ),
    ]
